version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
  library: 
    image: library:latest
    container_name: library
    pull_policy: never 
    build: 
      args:
        SERVICE: library
    restart: on-failure
    ports: 
      - "8060:8000"
  rating: 
    image: rating:latest
    container_name: rating
    pull_policy: never 
    build: 
      args:
        SERVICE: rating
    restart: on-failure
    ports: 
      - "8050:8000"
  reservation: 
    image: reservation:latest
    container_name: reservation
    pull_policy: never 
    build: 
      args:
        SERVICE: reservation
    restart: on-failure
    ports: 
      - "8070:8000"
  gateway: 
    image: gateway:latest
    container_name: gateway
    pull_policy: never 
    build: 
      args:
        SERVICE: gateway
    restart: on-failure
    ports: 
      - "8080:8000"
volumes:
  db-data: