version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
  library: 
    image: library:latest
    container_name: library
    pull_policy: never 
    build: 
      args:
        SERVICE: library
    environment: 
      PORT: 8060
      ALLOWED_HOSTS: "library,localhost"
    restart: on-failure
    ports: 
      - "8060:8060"
  rating: 
    image: rating:latest
    container_name: rating
    pull_policy: never 
    build: 
      args:
        SERVICE: rating
    environment: 
      PORT: 8050
      ALLOWED_HOSTS: "rating,localhost"
    restart: on-failure
    ports: 
      - "8050:8050"
  reservation: 
    image: reservation:latest
    container_name: reservation
    pull_policy: never 
    build: 
      args:
        SERVICE: reservation
    environment: 
      PORT: 8070
      ALLOWED_HOSTS: "reservation,localhost"
    restart: on-failure
    ports: 
      - "8070:8070"
  gateway: 
    image: gateway:latest
    container_name: gateway
    pull_policy: never 
    build: 
      args:
        SERVICE: gateway
    environment: 
      PORT: 8080
      ALLOWED_HOSTS: "gateway,localhost"
      LIBRARY_API_URL: "http://library:8060/api/v1"
    restart: on-failure
    ports: 
      - "8080:8080"
volumes:
  db-data: