# Generated by Django 5.1.3 on 2024-12-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_uid', models.UUIDField(unique=True, verbose_name='Reservation_uid')),
                ('username', models.CharField(max_length=80)),
                ('book_uid', models.UUIDField(verbose_name='Book_uid')),
                ('library_uid', models.UUIDField(verbose_name='Library_uid')),
                ('status', models.CharField(choices=[('RENTED', 'RENTED'), ('RETURNED', 'RETURNED'), ('EXPIRED', 'EXPIRED')], max_length=20)),
                ('start_date', models.DateTimeField()),
                ('till_date', models.DateTimeField()),
            ],
        ),
    ]
