# Generated by Django 5.1.3 on 2024-12-04 15:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsoi_reservation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_uid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Reservation_uid'),
        ),
    ]
