# Generated by Django 5.1.3 on 2024-12-04 20:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_uid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Books')),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('condition', models.CharField(choices=[('EXELLENT', 'EXELLENT'), ('GOOD', 'GOOD'), ('BAD', 'BAD')], default='EXELLENT', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_uid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Library_uid')),
                ('name', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_count', models.IntegerField(verbose_name='Availability')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsoi_library_app.books')),
                ('library_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsoi_library_app.library')),
            ],
        ),
    ]
