# Generated by Django 5.1.3 on 2024-11-30 13:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsoi_library_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='library_uid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Library_uid'),
        ),
    ]
