# Generated by Django 5.1.3 on 2024-12-06 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsoi_library_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='librarybooks',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='librarybooks',
            old_name='library_id',
            new_name='library',
        ),
    ]
