# Generated by Django 5.1.3 on 2024-12-04 15:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsoi_library_app', '0002_alter_library_library_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='books_uid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Books'),
        ),
    ]
